const actionTypes = {
  LOAD: 'CHARACTERS | LOAD_CHARACTERS',
  LOAD_SUCCESS: 'CHARACTERS | LOAD_CHARACTERS SUCCESS',
  LOAD_FAILURE: 'CHARACTERS | LOAD_CHARACTERS FAILURE',
}

export default actionTypes